// Package dnsinfra 提供 DNS 配置生成（CoreDNS hosts 段）。
package dnsinfra

import (
	"fmt"
	"strings"

	dnsdomain "github.com/vortexops/vortexops/internal/domain/dns"
)

// CoreDNSProvider 生成 CoreDNS 自定义 hosts 配置。
type CoreDNSProvider struct{}

// NewCoreDNSProvider 创建 provider。
func NewCoreDNSProvider() *CoreDNSProvider {
	return &CoreDNSProvider{}
}

// RenderHostsBlock 把活跃记录渲染为 CoreDNS hosts 插件配置段。
// 格式：多 A 记录（同 FQDN 多行指向不同 Pod IP）。
func (p *CoreDNSProvider) RenderHostsBlock(records []*dnsdomain.Record, backends map[int64][]dnsdomain.Backend) string {
	var b strings.Builder
	b.WriteString("# Generated by VortexOps DNS service\n")
	b.WriteString("hosts {\n")
	for _, rec := range records {
		if rec == nil || rec.Status != dnsdomain.StatusActive {
			continue
		}
		bs := backends[rec.ID]
		if len(bs) == 0 {
			continue
		}
		for _, be := range bs {
			if !be.Healthy || be.PodIP == "" {
				continue
			}
			fmt.Fprintf(&b, "  %s %s\n", be.PodIP, rec.FQDN)
		}
	}
	b.WriteString("  fallthrough\n")
	b.WriteString("}\n")
	return b.String()
}

// RenderCorefileSnippet 生成可嵌入 Corefile 的 vortexops 段。
func (p *CoreDNSProvider) RenderCorefileSnippet(hostsBlock string) string {
	if strings.TrimSpace(hostsBlock) == "" {
		return ""
	}
	return "vortexops.local:53 {\n" + hostsBlock + "  log\n  errors\n}\n"
}
